### ISSUE TITLE
[Feature Request] Progress delay/skipping

### ISSUE THREAD

**Issue by NickeManarin** [martinchrzan/FileTransferManager#5]
This request is not that important, because it can be implemented in another assembly, easily.
But if you'd like too, it can also be implemented in this project.

Basically, it's a simple way of avoiding UI flickering when transferring lots of small files, while using the progress reporting (content being displayed too rapidly, the user won't be able to see).

For example, you set 500ms as the progress skipping boundary, the progress can only be reported in intervals of 500ms, anything in between is ignored.

Example:
https://github.com/NickeManarin/FileTransferManager/blob/master/IOExtensions/FileTransferManager.cs#L142

**Comment by martinchrzan** [comment]
Thanks, but I will unfortunately not implement this feature because of 2 reasons:
1. I would like to keep this lib as simple as possible
2. This feature would be pushing some specifics of UI workflow here which is creating an abstraction leak and breaking single responsibility principle. Throttling, delaying or any action that is solely for the purpose of an UI should be kept in that UI and not pushed down here. I do also have such a problem in my application where I use this lib, but I handled that on a different layer.

**Comment by NickeManarin** [comment]
Oh, it's alright. Thank you anyway.
